### ISSUE TITLE
[wink] token expires with no mechanism for refresh

### ISSUE THREAD

**Issue by shawncrosby** [sebmarchand/openhab2-addons#4]
There doesn't appear to be a mechanism to refresh the access token when it expires.

## Expected Behavior
When the access token expires, the wink client should receive a 401 message back from the service and then automatically attempt to get a new token, persist it and then re-try the request with the new token. 

## Current Behavior
Currently when the access token expires, the handler doesn't deal with the 401 and produces a json parse exception so the handler just basically stops working with very little debugging.

## Possible Solution
In order to do a refresh, somehow the plugin has to do a number of things:
- needs the client id and secret along with the refresh token
- needs to persist the new token somewhere that the plugin can access it
- needs to handle 401 errors by invoking the refresh method and then retrying the current call in a seamless way.

This is difficult to do with the current design of putting somewhat transient tokens in the hub thing config file and having wink client logic intermingled in the handler code.  My suggestion is to move the token config values (perhaps just the initial access token) to a services file along with the client id and secret, persist the refresh and current access token somewhere in the userdata store (not completely sure how to do this in code, but I'm sure theres a way) and then encapsulate the wink client logic in a separate WinkClient component that knows how to deal with 401s or other issues that the thinghandler just calls when needed.  This will also make a much cleaner design IMHO.

## Steps to Reproduce (for Bugs)
1.  Set up the plugin with access code and refresh token in the thing file
2.  Wait until the token expires (I think 14 days)
3.  Notice nothing works and then go back and do a refresh manually

## Context
I just want to make the setup and maintenance of the plugin as simple as possible.  I'm happy to do the refactoring work and submit a pull request for it, but I thought I'd document the conversation here.

## Your Environment

* Version used: openhab 2.0 - personal build of the wink addon built july 2/17
* MacOS

**Comment by sebmarchand** [comment]
This seems much cleaner :), to be honest I haven't spent much time on the authentication part, I just got it to work and I focused on the rest of the binding... I'd also really like to find a way to use the Oauth2 workflow rather than asking the users to get their Wink client_id / secret.

I really don't have much time to work on this now, but I've no objection to this, so if you want to do it feel free to send me a pull request :) 

Thanks for the great feedback, this is really appreciated!

**Comment by shawncrosby** [comment]
Unless we created a cloud app in heroku or something to host the tokens, I don't see how you'd get away from individuals requiring their own app.  Pretty much all other plugins I've seen require users to get their own app id and secret to authenticate.  Maybe thats an idea for a service that someone could build and host, but my sense is that most in the community don't want a big brother minding all their keys...I doubt I would want that at least.

**Comment by sebmarchand** [comment]
Yeah, I didn't said that it was an easy thing to do or that it was doable :), I just thought that we might be able to do something similar to what they do in Home Assistant: https://home-assistant.io/components/wink/ (there's a web app to get your access token)

**Comment by shawncrosby** [comment]
this is fixed with PR #6
